### ISSUE TITLE
Browser tab in activity not showing browser data

### ISSUE THREAD

**Issue by lowwor** [ActivityWatch/aw-webui#205]
The aw-watcher-window is a little laggy in macOS. So i disable it (uncheck its module). As a result, in the web-ui, no data is shown( no Top Browser Domains and no Top Browser URLs) in the browser tab in activity panel. I think it's because the query of browser data is bound with the window data. Maybe we can decouple it because some people may only want to track its browser data.

**Comment by johan-bjareholt** [comment]
The reason why they are needed is because the browser does not expose if the window is focused or not as well as if the user is afk or not, so without merging the data from all those buckets the time will be very inaccurate and for most people most likely useless.

The solution should be to fix the window watcher on macOS, progress is being made so I hope we will have it fixed soon.

**Comment by lowwor** [comment]
Got it. Thanks for your quick response.
