### ISSUE TITLE
How to make changes to aw-webui and have them reflected when running aw-qt?

### ISSUE THREAD

**Issue by utkarshdalal** [ActivityWatch/aw-webui#226]
I've made some UI changes to the Vue app. When I run it with `npm run serve`, they display correctly.

When I then run `make build` in the root activitywatch folder, and then run `aw-qt`, the changes are not reflected on `http://localhost:5600/`. I've tried running `make uninstall` and tried deleting and recreating my virtualenv but this did not help. 

I'm not sure what I need to do to make changes to `aw-webui` and see them reflected when I run `aw-qt` and visit `http://localhost:5600/`

Help?

**Comment by billangli** [comment]
Hi @utkarshdalal, I believe that the problem is when you run `npm run serve`, it does not create/update files in the `aw-webui/dist` folder for the server to use. You should run `npm run build` instead. For more details between the two commands, check this out: https://cli.vuejs.org/guide/cli-service.html#vue-cli-service-serve.

When you run `make build` in the activitywatch folder, it might be because `SKIP_WEBUI` is defined somewhere and it would build `aw-webui` at all. You can check the makefiles to see the details or remove them.

As a heads up, we are also migrating to `aw-server-rust`.

**Comment by utkarshdalal** [comment]
Thanks @billangli - I think `SKIP_WEBUI` was being defined somehow. I manually ran `make aw_webui` in the `aw-server` folder and this seemed to fix the issue.
