### ISSUE TITLE
Add logging utility

### ISSUE THREAD

**Issue by iloveitaly** [ActivityWatch/aw-webui#285]
Thoughts on adding in a simple logging utility like https://github.com/pimterry/loglevel? Would help eliminate `console.log` from the codebase, but also encourage helpful logging throughout the codebase that can be enabled during development.

**Comment by iloveitaly** [comment]
@ErikBjare what do you think on this?

**Comment by ErikBjare** [comment]
Not convinced of the benefit of this, as browser dev tools already have toggles to control the log level at the UI level (if you use `console.debug`, `console.warn`, `console.info`, etc). 

If this was a node app and not a web app I'd be 100% for it, but I don't really see the benefit of handing over log level control to the code itself, given that browsers already let you do that on your own terms.

Perhaps a good first step would be to change all `console.log` to their respective level-specified counterparts, and then see if there's a need from there?

**Comment by iloveitaly** [comment]
@ErikBjare The only downside with your proposed approach is I don't believe there's a way to set the log level in code, so users would always see the log messages (regardless of the level set) if they open up the dev console.

This isn't a huge issue, and may be worth it given the simplicity gains of not using another package for managing log levels.

**Comment by iloveitaly** [comment]
@ErikBjare curious what you think about my last comment. Another thing to consider is we could use a library with good structured logging support, which would be helpful for debugging.

**Comment by ErikBjare** [comment]
> The only downside with your proposed approach is I don't believe there's a way to set the log level in code, so users would always see the log messages (regardless of the level set) if they open up the dev console.

My point is: why do you want to filter the logs by level in the code when you can just use the dev console filters?

![image](https://user-images.githubusercontent.com/1405370/142882872-8321addb-813d-445f-b92f-e62d73d265c9.png)

Why have a second way to do the same thing? Filtering logs before they're logged to the console would make it harder to control which logs you see (having to rebuild the web UI, perhaps restart the server, etc). Because of this, if I were a new dev I'd not expect it to pre-filter the logs before the dev tools filters (principle of least astonishment).

> Another thing to consider is we could use a library with good structured logging support, which would be helpful for debugging.

Not convinced of the usefulness of this, or at least I can't remember a time where it would have been helpful. imo/ime, structured logging is generally only useful when you're expected to save & process the logs further, which isn't really the case for the webui logs. We used to have structured logging support for aw-server-python, but even there we removed it because it didn't turn out to be useful.

This issue feels like it's bordering on bikeshedding imo, so closing. If I've misunderstood your point, feel free to reply.
