### ISSUE TITLE
Show only Hour+Minutes

### ISSUE THREAD

**Issue by guettli** [ActivityWatch/aw-webui#494]
I highlighted what I care about:

![image](https://github.com/ActivityWatch/aw-webui/assets/414336/f3ac2c78-ca9e-42de-8d4e-b1d6ec2c8328)

I only want to see the hour and the minutes.

I don't care for the year, month, day and seconds.

It would be great if you could customize the date format.

**Comment by ErikBjare** [comment]
Thanks for the feedback!

In https://github.com/ActivityWatch/aw-webui/commit/54be44d46cfa4006b0aea661e08a54962f3fd842 I changed it so that:
- the date is only shown if the event crosses a date boundary
- only show `HH:mm:ss` (never show the timezone)

It's not *exactly* what you asked for, but I think it covers 99% of people's expectations without having to add another setting :)

**Comment by guettli** [comment]
@ErikBjare thank you very much!
