### ISSUE TITLE
(Some) settings from the database are ignored

### ISSUE THREAD

**Issue by BelKed** [ActivityWatch/aw-webui#568]
(Some) settings that aren't saved in **Local Storage** are ignored by **ActivityWatch**. For example, the landing page setting — even if it is changed to **Activity (unknown)** (`/activity/unknown/view/`), the default homepage will be loaded:

![Screenshot](https://github.com/ActivityWatch/aw-webui/assets/66956532/b11e23f2-3e48-4cd4-bbff-c9971ee9ff3b)

---

Another example is using the default categorization even if a custom one is in the database and also loaded in the web UI by a request (`/api/0/settings`).

**Comment by ErikBjare** [comment]
The issue of landing page settings I "fixed", but had to revert due to it not being initialized on time: https://github.com/ActivityWatch/aw-webui/commit/6bffa6527802f45146044389f56e8a7a4b8ab088#comments

I'm not really sure how to fix that one, except try to keep a value around in localStorage that gets refreshed on every settings fetch (which might not be happening right now).
