### ISSUE TITLE
Start using Vuetify

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/aw-webui#88]
I've been working on [Thankful](https://github.com/SuperuserLabs/thankful) over the summer and been realizing how amazing Vuetify is.

It would likely improve the UX a lot, and would make things a lot easier to maintain. Migrating shouldn't even be that hard, so I might give it a shot some point soon.

Material design might not be perfect, but I certainly think it beats what we have currently, and Vuetify is just sooooo much nicer.

[The datepicker](https://vuetifyjs.com/en/components/date-pickers) even has a prop for "allowed dates" (as discussed in https://github.com/ActivityWatch/aw-webui/issues/22).

Useful things:

 - https://vuetifyjs.com/en/components/alerts
 - https://vuetifyjs.com/en/components/cards
 - https://vuetifyjs.com/en/components/tabs
 - https://vuetifyjs.com/en/components/date-pickers
 - https://vuetifyjs.com/en/components/expansion-panels
 - https://vuetifyjs.com/en/components/progress
   - While queries are running
 - https://github.com/vuetifyjs/vuetify/issues/238: [Feature Request] Uploader component 
   - When we start implementing import

**Comment by johan-bjareholt** [comment]
I'm fine with Vuetify except one thing which I honestly disgust, and that is the sidebar which is used on both vuerifys homepage and recently added to Thankful.

Reasons:
- Hiding it by default is horrible on the desktop
    - There is so much screen real-estate, why hide it?
    - It is hard to find for the user since the "slide-out from the side" touch motion is not natural on the desktop so you don't expect a hidden sidebar to exist
- If overflowing (as on vuetifys sidebar) the native scrollbar of my browser does not fit with the design at all
    - Having so many items in the first place in the sidebar doesn't fly with me
- Most websites have the navigation on the top, moving it to a sidebar feels wrong on the desktop since that's not where you expect it to be
- And more

</end_of_rant>

**Comment by ErikBjare** [comment]
Yeah not a huge fan of the sidebar either, we could go with something else.

**Comment by ErikBjare** [comment]
Started working on it in #90

**Comment by johan-bjareholt** [comment]
Can we close this?

**Comment by ErikBjare** [comment]
Yeah, not gonna happen.
