### ISSUE TITLE
"Top Applications" category includes software which runs automatically in the background

### ISSUE THREAD

**Issue by nicolae-stroncea** [ActivityWatch/aw-webui#95]
I think a good addition would be a button which gives the option of including background apps or not, similar to the button "Filter away afk time". This would include apps like SearchUI.exe and ApplicationFrameHost.exe. 

Is there a way to differentiate between apps like these and apps that the user directly interacts with and does ActivityWatch currently do that?

**Comment by ErikBjare** [comment]
@nicolae-stroncea You're right! Something like that would be preferred, the only issue is that there is currently no way to persist settings to the server currently. 

We could store it in the browser session, but I'd expect the server to persist my settings so that would require adding an API endpoint to the server for UI config storage.
